### ISSUE TITLE
Probleme base manager

### ISSUE THREAD

**Issue by BenjaminPorquet** [skwi/SkwiProjectBaseBundle#1]
Bonjour,

Pourquoi avoir remplacé l'ancien code : 

```
protected function getManagedType()
{
$matches = [];
if (preg_match('#DoctrineORM(Entity|Document)Manager_\w{64}#', get_class($this->om), $matches)) {
return $matches[1];
}

    $type = substr(get_class($this->om), strrpos(get_class($this->om), '\\') + 1);
    $type = str_replace('Manager', '', $type);

    return $type;
}
```

Par ce nouveau : 
```

    protected function getManagedType()
    {
        $type = substr(get_class($this->om), strrpos(get_class($this->om), '\\') + 1);
        $type = str_replace('Manager', '', $type);
        return $type;
    }
```

En effet, ca genere une erreur désormais : 

<img width="1440" alt="capture d ecran 2018-02-14 a 10 03 49" src="https://user-images.githubusercontent.com/12295662/36195625-5ed2c342-116e-11e8-8582-d7bea274ee9b.png">

merci

**Comment by skwi** [comment]
Bonjour, 

le contenu de cette méthode avait été altéré lors de la restauration du Bundle.

L'utilisation de l'expression régulière pour identifier les classes proxy vient d'être restaurée.
Elle est disponible dans [la version 2.4.2](https://github.com/skwi/SkwiProjectBaseBundle/releases/tag/2.4.2).

**Comment by BenjaminPorquet** [comment]
Ok merci 👍
