### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by Benjamin-Porquet** [skwi/SkwiProjectBaseBundle#18]
Is it compatible with SF3 ?

I have an error on the ORDER BY 

An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT id_0 FROM (SELECT g0_.id AS id_0, g0_.title AS title_1, g0_.description AS description_2, g0_.url AS url_3, g0_.startHour AS startHour_4, g0_.stopHour AS stopHour_5, g0_.position AS position_6, g0_.state AS state_7 FROM group_of_tasks g0_) dctrn_result ORDER BY position_6 ASC LIMIT 25 OFFSET 0':

SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'dctrn_result.position_6' which is not in SELECT list; this is incompatible with DISTINCT")

thanks

**Comment by skwi** [comment]
Hi Benjamin,

the bundle is not maintained any longer.
Therefore, it's compatibility with Symfony 3.X is not guarantied.

However, your problem doesn't seem to be related to the symfony version.

You are grouping by the property `position` on the table `group_of_tasks`, but you only select the property `id` of this same table. SQL does not allow you to group by a field that is not selected to be displayed in the query result.

**Comment by Benjamin-Porquet** [comment]
Hi,

Hum, ok thanks, you can close this issue :)
